# Generated by Django 5.2.6 on 2025-09-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(blank=True, null=True, upload_to="jds/")),
                ("text_content", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="resume",
            name="candidate_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
